package tech.jdev.rest_api_forum.entity;

public enum Course {
    SISTEMAS_DE_INFORMACAO,
    CIENCIA_DA_COMPUTACAO,
    ENGENHARIA_DE_SOFTWARE,
    REDES_DE_COMPUTADORES,
    ENGENHARIA_DA_COMPUTACAO,
    DESIGN_DIGITAL
}